server:
  # 0은 랜덤 포트(정적) == 객체는 한 개밖에 안 나옴.
  port: 0
#  port: 9001

spring:
    application:
      name: spring-cloud-user-service

eureka:
  # 랜덤(동적)
  instance:
    # 10.10.100.60:spring-cloud-user-service:9001 == ${10.10.100.60}$:{spring-cloud-user-service:${9001}}
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    # Eureka 서버로부터 객체의 정보를 주기적으로 가져올 것인지 속성
    # True, 갱신된 정보를 받겠다.
    fetch-registry: true
    service-url:
      # 등록할 서버의 위치
      defaulZone: http://127.0.0.1:8761/eureka

# vm option :     -Dserver.port=9002
